package worker

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/TEENet-io/ai-env-mgr/internal/slsclient"
)

// SLSArchive answers "did these audit events arrive" by querying the log
// service for their ids.
//
// It is the reason written and confirmed are separate states: without an
// answer from the far end, "delivered" would mean "we wrote a line to a file",
// and an audit trail that is quietly incomplete is worse than one that is
// visibly behind.
type SLSArchive struct {
	Client *slsclient.Client
	// PerQuery bounds how many ids go into one search expression. The service
	// takes a long query but not an unbounded one, and a query that is
	// rejected for length would look exactly like an event that never arrived.
	PerQuery int
}

// Contains reports which of the given event ids are present in the logstore
// between from and to.
func (a SLSArchive) Contains(ctx context.Context, logstore string, eventIDs []string, from, to time.Time) (map[string]bool, error) {
	present := make(map[string]bool, len(eventIDs))
	if a.Client == nil || len(eventIDs) == 0 {
		return present, nil
	}
	perQuery := a.PerQuery
	if perQuery <= 0 {
		perQuery = 50
	}

	for start := 0; start < len(eventIDs); start += perQuery {
		end := min(start+perQuery, len(eventIDs))
		chunk := eventIDs[start:end]

		terms := make([]string, 0, len(chunk))
		for _, id := range chunk {
			// Ids are uuids generated by the database, so there is nothing to
			// escape; quoting them keeps the hyphens from being read as
			// operators.
			terms = append(terms, fmt.Sprintf("event_id: %q", id))
		}
		query := strings.Join(terms, " or ")

		result, err := a.Client.GetLogs(ctx, logstore, query,
			from.Unix(), to.Unix(), len(chunk), 0, false)
		if err != nil {
			return nil, err
		}
		if !result.Complete {
			// The index was still catching up, so an absent id here means
			// nothing. Reporting these as missing would raise an alarm about
			// the archive being slow.
			continue
		}
		for _, log := range result.Logs {
			if id := log["event_id"]; id != "" {
				present[id] = true
			}
		}
	}
	return present, nil
}
